use_frameworks!

platform :ios, '10.0'

target 'ATListViewController_Example' do
  
  pod 'YYModel'
  pod 'LookinServer', :configurations => ['Debug']
  
  pod 'ATListViewController', :path => '../'

  target 'ATListViewController_Tests' do
    inherit! :search_paths

    
  end
  
end
